#!/usr/bin/env python3
import subprocess

def main():
	window_name = subprocess.getoutput("xdotool getwindowfocus getwindowname").lower()
	xournal = "xournal" in window_name; #"Xournal"
	stylus_labs = "stylus labs write" in window_name;#"Stylus Labs Write"
	gedit = "gedit" in window_name;
	if stylus_labs or xournal or gedit:
		subprocess.call("xdotool key ctrl+s".split());
		subprocess.call("evemu_do key Alt+F4".split());
	else:
		subprocess.call("evemu_do key Alt+F4".split());
	


if __name__ == '__main__':
	main()
